name: radiotrib
description: "RADIO TRIB ESTE MUZICA TARE PENTRU PRIETENI"
publish_to: 'none'
version: 1.0.3+4

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  http:
  just_audio:
  audio_service:
  audio_session:

  flutter_launcher_icons:
  flutter_native_splash:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:
  uses-material-design: true
  assets:
    - assets/splash/fullscreen.png
    - assets/background/background.png
    - assets/icon/trib.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path_ios: "assets/icon/trib.png"
  remove_alpha_ios: true
  image_path_android: "assets/icon/trib.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/icon/trib.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/splash/fullscreen.png
  android_gravity: center
  ios_content_mode: scaleAspectFit
  fullscreen: true
  android_12:
    image: assets/splash/tribnativelogo.png
    icon_background_color: "#000000"
    android_gravity: center

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/logoradiotrib.png"